### ISSUE TITLE
DB remains unitialized

### ISSUE THREAD

**Issue by FlyingBird95** [greyli/todoism#6]
Hi,

I've done the following commands (as specified in your readme):
```git clone https://github.com/greyli/todoism.git
cd todoism
pipenv install --dev
pipenv shell
flask run
```

But, I get the following error (when trying to register an user):
```
"GET /register HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/.../git/todoism/todoism/blueprints/auth.py", line 51, in register
    while User.query.filter_by(username=username).first() is not None:
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2888, in first
    ret = list(self[0:1])
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2680, in __getitem__
    return list(res)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/.../.local/share/virtualenvs/venv/todoism/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user [SQL: 'SELECT user.id AS user_id, user.username AS user_username, user.password_hash AS user_password_hash, user.locale AS user_locale \nFROM user \nWHERE user.username = ?\n LIMIT ? OFFSET ?'] [parameters: ('randyrichardson', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

What do I need to do to fix this error?

Thanks in advance,

Patrick

p.s. Really nice project!

**Comment by greyli** [comment]
I just updated the README, try this one:
```
$ cd todoism
$ pipenv install --dev
$ pipenv shell
$ flask initdb
$ flask translate compile
$ flask run
```
